version: '3.7'

x-base-dev: &base-dev
  restart: on-failure

services:

  python:
    <<: *base-dev
    build:
      context: .
      target: python
    volumes:
      - ./src:/src
      - .:/project

  bigsmokepython:
    <<: *base-dev
    image: salimfadhley/bigsmoke_python:latest
    build:
      context: .
      target: bigsmokepython
    volumes:
      - ./src:/src
      - .:/project




